// World champions actions
export const REQUEST_WORLD_CHAMPIONS = 'REQUEST_WORLD_CHAMPIONS';
export const COMPLETE_WORLD_CHAMPIONS_REQUEST = 'COMPLETE_WORLD_CHAMPIONS_REQUEST';

export const REQUEST_NUMBER_OF_WORLD_CHAMPIONS = 'REQUEST_NUMBER_OF_WORLD_CHAMPIONS';

// Winners in a season actions
export const REQUEST_WINNERS_BY_YEAR = 'REQUEST_WINNERS_BY_YEAR';
export const COMPLETE_WINNERS_BY_YEAR_REQUEST = 'COMPLETE_WINNERS_BY_YEAR_REQUEST';

export const REQUEST_NUMBER_OF_WINNERS_IN_SEASON = 'REQUEST_NUMBER_OF_WINNERS_IN_SEASON';
export const COMPLETE_NUMBER_OF_WINNERS_IN_SEASON_REQUEST = 'COMPLETE_NUMBER_OF_WINNERS_IN_SEASON_REQUEST';

export const OPEN_WINNERS_BY_YEAR_POPUP = 'OPEN_WINNERS_BY_YEAR_POPUP';
export const CLOSE_WINNERS_BY_YEAR_POPUP = 'CLOSE_WINNERS_BY_YEAR_POPUP';

// Notification actions
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const CLOSE_NOTIFICATION = 'CLOSE_NOTIFICATION';
