export const HANDLE_ALL_CHAMPIONS_REQUEST = "HANDLE_ALL_CHAMPIONS_REQUEST";
export const COMPLETE_ALL_CHAMPIONS_REQUEST = "COMPLETE_ALL_CHAMPIONS_REQUEST";
export const COMPLETE_CHAMPION_REQUEST = "COMPLETE_CHAMPION_REQUEST";
export const HANDLE_ALL_CHAMPIONS_BY_YEAR_REQUEST = "HANDLE_ALL_CHAMPIONS_BY_YEAR_REQUEST";
export const COMPLETE_ALL_CHAMPIONS_BY_YEAR_REQUEST = "COMPLETE_ALL_CHAMPIONS_BY_YEAR_REQUEST";
export const HANDLE_OPEN_CHAMPIONS_BY_YEAR_POPUP = "HANDLE_OPEN_CHAMPIONS_BY_YEAR_POPUP";
export const CLOSE_CHAMPIONS_BY_YEAR_POPUP = "CLOSE_CHAMPIONS_BY_YEAR_POPUP";