export const HANDLE_TEST_SAGA = "HANDLE_TEST_SAGA";
export const HANDLE_ALL_CHAMPIONS_REQUEST = "HANDLE_ALL_CHAMPIONS_REQUEST";
export const COMPLETE_ALL_CHAMPIONS_REQUEST = "COMPLETE_ALL_CHAMPIONS_REQUEST";